export const metadata = {
  title: 'Berita - GenBI UINAM',
  description: 'Generated by GenBI UINAM.',
}

const LayoutBerita = ({ children }) => {
  return <section>{children}</section>;
};

export default LayoutBerita;
