import { DrawerProvider } from "@/contexts/DrawerContext";
import Head from "next/head";
import "./globals.css";
// import

export const metadata = {
  title: "GenBI UINAM",
  description: "Generated by GenBI UINAM.",
  keywords: [
    "genbiuinam.org",
    "website genbi",
    "genbiuinam",
    "genbi uin",
    "genbi",
  ],
  authors: [{ name: "genbiuinam", url: "https://genbiuinam.org" }],
  icons: {
    icon: "https://genbiuinam.org/icon.png",
  },
  openGraph: {
    title: "GenBI UINAM",
    description: "Generated by GenBI UINAM.",
    images: [
      {
        url: "https://genbiuinam.org/icon.png",
        width: 800,
        height: 600,
        alt: "GenBI UINAM",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="google-site-verification"
          content="Wofa18OhY74s7uT9g6tr39j2BE67VWKfsW4lDaz7QHk"
        />
        <link rel="icon" href="/icon.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/180pixel.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/32cm.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/16cm.png" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: `
          {
            "@context": "http://schema.org",
            "@type": "Organization",
            "url": "https://www.genbiuinam.org",
            "logo": "https://www.genbiuinam.org/icon.png"
          }
        `,
          }}
        />
      </Head>
      <body style={{ fontFamily: "myFont", margin: 0, padding: 0 }}>
        <DrawerProvider>{children}</DrawerProvider>
      </body>
    </html>
  );
}
