export const metadata = {
  title: "GenBI UINAM",
  description: "Generated by GenBI UINAM",
};

const LayoutLogin = ({ children }) => {
  return <section>{children}</section>;
};

export default LayoutLogin;
