export const metadata = {
  title: "Tentang - GenBI UINAM",
  description: "Generated by GenBI UINAM.",
  keywords: [
    "genbiuinam.org",
    "tentang genbiuinam",
    "genbiuinam",
    "genbi uin",
    "genbi",
  ],
  authors: [{ name: "tentang genbiuinam", url: "https://genbiuinam.org/tentang_kami" }],
  icons: {
    icon: "https://genbiuinam.org/icon.png",
  },
  openGraph: {
    title: "Tentang - GenBI UINAM",
    description: "Generated by GenBI UINAM.",
    images: [
      {
        url: "https://genbiuinam.org/icon.png",
        width: 800,
        height: 600,
        alt: "GenBI UINAM",
      },
    ],
  },
};

const LayoutTentangKami = ({ children }) => {
  return <section>{children}</section>;
};

export default LayoutTentangKami;
