export const metadata = {
    title: "GenBI UINAM",
    description: "Generated by GenBI UINAM",
  };
  
  const LayoutDashboardPengurus = ({ children }) => {
    return <section>{children}</section>;
  };
  
  export default LayoutDashboardPengurus;
  